remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tutorial Index
description: Index of Berkeley SCF training materials.
show_downloads: false
logo: assets/img/svg_Vertical_No_Endorser.svg
