project:
  type: website

website:
  site-url: https://computing.stat.berkeley.edu
  title: "Computing in the Department of Statistics"
  #description: ""
  sidebar:
    style: docked
    logo: assets/img/svg_Vertical_No_Endorser.svg
    contents:
      - href: index.qmd
      - href: tutorials.qmd
      - href: motd.qmd

format:
  html:
    theme: cosmo
    toc: true
